services:
  miningbots-competition-manager:
    image: miningbots-competition-manager
    build: .
    init: true
    container_name: miningbots-competition-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/mcm-submodules:/data/mcm-submodules
      - /data/mcm-data:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SECRET_KEY=${SECRET_KEY:?}
      - POSTGRES_CONNECT_URI=${POSTGRES_CONNECT_URI:?}
      - fe_host=${fe_host:?}
    healthcheck:
      test: ["CMD", "python3", "healthcheck.py"]
      interval: 1m30s
      timeout: 10s
      retries: 3
